<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="5" hostname="DESKTOP-BG83L86" failures="1" tests="12" name="Test" time="8.436" errors="0" timestamp="2024-12-29T15:48:31 IST">
  <testcase classname="com.bank.api.tests.AuthenticationTests" name="verifySignUpWithAlreadyExistUser" time="1.879"/>
  <testcase classname="com.bank.api.tests.AuthenticationTests" name="verifyLoginWithInvalidCredentials" time="0.885"/>
  <testcase classname="com.bank.api.tests.AuthenticationTests" name="verifyLoginWithValidCredentials" time="0.41"/>
  <testcase classname="com.bank.api.tests.AuthenticationTests" name="verifyForgotPasswordWithValidEmail" time="0.227"/>
  <testcase classname="com.bank.api.tests.UserProfileManagementTests" name="verifyGetUserProfile" time="0.427"/>
  <testcase classname="com.bank.api.tests.UserProfileManagementTests" name="verifyUpdateUserProfileWithPutRequest" time="0.202"/>
  <testcase classname="com.bank.api.tests.UserProfileManagementTests" name="verifyUpdateUserProfileWithPatchRequest" time="0.154"/>
  <testcase classname="com.bank.api.tests.UserProfileManagementTests" name="verifyChangePassword" time="0.351"/>
  <testcase classname="com.bank.api.tests.UserProfileManagementTests" name="verifyDeleteUserProfile" time="2.179">
    <failure type="java.lang.AssertionError" message="expected [User profile deleted successfully] but found [{
    &amp;quot;timestamp&amp;quot;: &amp;quot;Sun Dec 29 10:18:30 UTC 2024&amp;quot;,
    &amp;quot;status&amp;quot;: 401,
    &amp;quot;error&amp;quot;: &amp;quot;Unauthorized&amp;quot;,
    &amp;quot;message&amp;quot;: &amp;quot;Full authentication is required to access this resource&amp;quot;,
    &amp;quot;path&amp;quot;: &amp;quot;/error&amp;quot;
}]">
      <![CDATA[java.lang.AssertionError: expected [User profile deleted successfully] but found [{
    "timestamp": "Sun Dec 29 10:18:30 UTC 2024",
    "status": 401,
    "error": "Unauthorized",
    "message": "Full authentication is required to access this resource",
    "path": "/error"
}]
at com.bank.api.tests.UserProfileManagementTests.verifyDeleteUserProfile(UserProfileManagementTests.java:111)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- verifyDeleteUserProfile -->
  <testcase classname="com.bank.api.tests.AccountTests" name="verifyCreateUserAccount" time="0.535"/>
  <testcase classname="com.bank.api.tests.AccountTests" name="verifyGetUserAccountByAccountNumber" time="0.15"/>
  <testcase classname="com.bank.api.tests.AccountTests" name="verifyGetUserAccounts" time="0.204"/>
  <testcase classname="com.bank.api.base.BaseTest" name="@BeforeSuite extentReportSetup" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite extentReportSetup -->
  <testcase classname="com.bank.api.base.BaseTest" name="@AfterSuite tearDown" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite tearDown -->
  <testcase classname="com.bank.api.base.BaseTest" name="@AfterSuite tearDown" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite tearDown -->
  <testcase classname="com.bank.api.tests.AuthenticationTests" name="verifySignUpWithValidData" time="0.0">
    <ignored/>
  </testcase> <!-- verifySignUpWithValidData -->
  <testcase classname="com.bank.api.base.BaseTest" name="@BeforeSuite extentReportSetup" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite extentReportSetup -->
</testsuite> <!-- Test -->
